[build]
target-dir = "./.temp/target/"

[publish]
target-dir = "./.temp/deploy/"
binaries = [
    "jvii",
    "jvii.exe",

    "jvn",
    "jvn.exe",

    "jvn_comp",
    "jvn_comp.exe",

    # Dynamic Lib
    "libjvcli.so",
    "libjvcli.dll",
]

#####################
### Bash/Zsh/Fish ###
#####################

# Completions
[copies.completion_jvn_bash]
from = "scripts/deploy/completions/bash.sh"
to = "comp/comp.sh"
platform = [ "linux", "macos" ]

[copies.completion_jvn_zsh]
from = "scripts/deploy/completions/zsh.zsh"
to = "comp/comp.zsh"
platform = [ "linux", "macos" ]

[copies.completion_jvn_fish]
from = "scripts/deploy/completions/fish.fish"
to = "comp/comp.fish"
platform = [ "linux", "macos" ]

# Entries
[copies.entry_bash]
from = "scripts/deploy/jvn_bash.sh"
to = "jvn_bash.sh"
platform = [ "linux", "macos" ]

[copies.entry_zsh]
from = "scripts/deploy/jvn_zsh.zsh"
to = "jvn_zsh.zsh"
platform = [ "linux", "macos" ]

[copies.entry_fish]
from = "scripts/deploy/jvn_fish.fish"
to = "jvn_fish.fish"
platform = [ "linux", "macos" ]

##################
### Powershell ###
##################

# Completions
[copies.completion_jvn_powershell]
from = "scripts/deploy/completions/powershell.ps1"
to = "comp/comp.ps1"
platform = [ "windows" ]

# Entries
[copies.entry_powershell]
from = "scripts/deploy/jvn.ps1"
to = "jvn.ps1"
platform = [ "windows" ]

##################
### Zsh Plugin ###
##################

# Not yet :(
